### ISSUE TITLE
A busca encontra apenas o nome idêntico e completo do autor

### ISSUE THREAD

**Issue by sacboulardii** [Maximos007/AppBook#6]
Quando digitamos apenas o primeiro nome, ou o nome incompleto do autor, a busca retorna sem resultados. 

Que tal o método de String **startsWith** ao invés de `book.author === nameAuthor`?

Por exemplo, `"Augusto Cury".startsWith("Au")` é **true**, assim como `startsWith("Augusto")`, então `book.author.startsWith(nameAuthor)` seria uma validação mais abrangente.

E o segundo problema é validar a busca em letras minúsculas e maiúsculas, para isso eu sugiro outro método de String chamado **toLowerCase**.

Nesse link tem algumas formas de comparar duas strings ignorando a diferença de letras maiúsculas e minúsculas. A mais básica é transformando as duas com str.toLowerCase().

https://masteringjs.io/tutorials/fundamentals/compare-strings-ignore-case#:~:text=The%20most%20basic%20way%20to,all%20lowercase%20or%20all%20uppercase.

**Comment by Maximos007** [comment]
:heavy_check_mark:  String startsWith
:heavy_check_mark: toLowerCase
